server {
    listen 80;
    server_name kipu.ec; # Cambia por tu dominio real
    root /usr/share/nginx/html;
    index index.html;

    # Cabeceras de seguridad básicas
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";

    # URLs limpias
    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    # Bloquear acceso a archivos sensibles (como el .env si estuviera ahí)
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # Cache de activos
    location ~* \.(css|js|ico|png|jpg|webp|woff2|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Error 404 personalizado (opcional)
    error_page 404 /404.html;
}
